name: Master Branch

on:
  push:
    branches:
      - 'develop'

jobs:

  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8.0
      - name: Maven Package

  sonar:
    name: SonarCloud - Scan & Publish
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8.0
      - name: SonarCloud Scan
        run: mvn -B clean sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

